name: Cache NuGet Packages

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up NuGet CLI (built-in on Windows)
        run: nuget help

      - name: Create packages directory
        run: mkdir nuget-packages

      - name: Install NuGet package (e.g., Newtonsoft.Json)
        run: nuget install Newtonsoft.Json -OutputDirectory nuget-packages

      - name: Check output
        run: |
          dir nuget-packages
          dir nuget-packages\Newtonsoft.Json*

      - name: Upload NuGet packages as artifact
        uses: actions/upload-artifact@3.0
        with:
          name: nuget-cache
          path: nuget-packages
