name: Monitor GitHub Variables

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch current repo variables
        id: fetch_vars
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/variables \
            | jq . > current-vars.json

      - name: Load previous vars if they exist
        run: |
          if [ -f previous-vars.json ]; then
            echo "Found previous vars
